piro21_Ajax_Pirostagram/apps/posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', main, name='main'),
    path('create/', create, name='create'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('update/<int:pk>/', update, name='update'),
    path('like_ajax/', like_ajax, name='like_ajax'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('search/', search, name='search'),
    path('comment_ajax/', comment_ajax, name="comment_ajax"),
    path('delete_comment_ajax/', delete_comment_ajax, name="delete_comment_ajax"),
]

piro21_Ajax_Pirostagram/apps/users/urls.py
from django.urls import path
from .views import *

app_name='users'

urlpatterns = [
    path('list/', list, name='list'),
    path('create', create, name='create'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('update/<int:pk>/', update, name='update'),
    path('search_user/', search_user, name='search_user'),
]

piro21_Ajax_Pirostagram/config/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.posts.urls')),
    path('users/', include('apps.users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

piro21_Ajax_Pirostagram/apps/posts/models.py
from django.db import models
from apps.users.models import User
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    author=models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자', null=True)
    title=models.CharField(max_length=300)
    image=models.ImageField(upload_to='posts/%Y%m%d')
    text=models.TextField()
    like=models.IntegerField()
    created_date = models.DateTimeField('작성일', auto_created=True, auto_now_add=True)
    updated_date = models.DateTimeField('수정일', auto_created=True, auto_now=True)

    def author_image(self):
        return self.author.profile_photo if self.author else None
    
class Comment(models.Model):
    post=models.ForeignKey(Post, related_name='comments',on_delete=models.CASCADE)
    writer=models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    content=models.TextField()
    created=models.DateTimeField(default=timezone.now, verbose_name="작성일")
    deleted=models.BooleanField(default=False, verbose_name="삭제여부")

piro21_Ajax_Pirostagram/apps/users/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    name=models.CharField(max_length=30)
    profile_photo = models.ImageField(upload_to='profile_photo/', blank=True, null=True)
    
    def __str__(self):
        return f'{self.name}'

piro21_Ajax_Pirostagram/apps/posts/forms.py
from django import forms
from .models import Comment, Post

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('__all__')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class SortForm(forms.Form):
    SORT_CHOICES = [
        ('등록순', '등록순'),
        ('최신순', '최신순'),
        ('이름순', '이름순'),
    ]
    sort_by = forms.ChoiceField(
        label='정렬',
        choices=[('','--정렬기준--')] + SORT_CHOICES,
        required=False,
        widget=forms.Select(
            attrs={
                'class': 'sort-input',
                'id': 'sort-options'
            }
        )
    )

piro21_Ajax_Pirostagram/apps/users/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ('__all__')

piro21_Ajax_Pirostagram/apps/posts/views.py
from django.shortcuts import render, redirect
from .models import Post, User, Comment
from .forms import PostForm, CommentForm, SortForm

# Create your views here.
    
def main(request):
    sort_form = SortForm(request.GET)
    sort_by = request.GET.get('sort_by', '등록순')
    
    if sort_by == '이름순':
        posts = Post.objects.order_by('title')
    elif sort_by == '최신순':
        posts = Post.objects.order_by('-id')
    else:
        posts = Post.objects.order_by('id')

    context= {
        'posts':posts,
        'sort_form':sort_form,
    }
    return render(request, 'post_list.html', context)

def detail(request, pk):
    author=User.objects.get(id=pk)
    posts=Post.objects.filter(author=author)
    context={
        'author':author,
        'posts':posts,
    }
    return render(request, 'post_detail.html', context)

def create(request):
    if request.method=="GET":
        form=PostForm()
        context={'form':form}
        return render(request, 'post_create.html', context)
    
    form=PostForm(request.POST, request.FILES)
    if form.is_valid():
        post=form.save()
        return redirect('posts:main')
    context={'form':form}
    return render(request, 'post_create.html', context)

def delete(request, pk):
    post=Post.objects.get(id=pk).delete()
    return redirect('posts:main')

def update(request, pk):
    post=Post.objects.get(id=pk)
    if request.method=="GET":
        form=PostForm(instance=post)
        context={'form':form, 'pk':pk}
        return render(request, 'post_update.html', context)
    
    form=PostForm(request.POST, request.FILES, instance=post)
    if form.is_valid():
        form.save()
    return redirect("posts:detail", pk=post.author.pk)
    
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json

@csrf_exempt
def like_ajax(request):
    req=json.loads(request.body)
    post_id=req['id']
    button_type=req['type']

    post=Post.objects.get(id=post_id)

    if button_type=='like':
        post.like+=1

    elif button_type == 'cancel':
        post.like -= 1

    post.save()

    return JsonResponse({'id':post_id, 'like_count':post.like})

def search(request):
    search_txt = request.GET.get("search_txt", "")
    posts = Post.objects.all()
    if search_txt:
        posts = Post.objects.filter(title__icontains=search_txt)
        
    results = [
        {
            'title': post.title,
            'content': post.text,
            'author': post.author.name if post.author else 'Unknown',
            'created_at': post.created_date.strftime('%Y-%m-%d %H:%M:%S'),
            'image': post.image.url if post.image else '',
        } for post in posts
    ]

    return JsonResponse(results, safe=False)

@csrf_exempt   
def comment_ajax(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        content = data.get('content')
        post_id = data.get('post_id')
        post = Post.objects.get(id=post_id)
        comment = Comment.objects.create(post=post, content=content)
        comment.save()
        ret = {
            'content': comment.content,
            'comment_id': comment.id,
            'post_id':post_id
        }
        return JsonResponse(ret)
    
@csrf_exempt
def delete_comment_ajax(request):
    if request.method=="POST":
        data = json.loads(request.body)
        comment_id=data.get('comment_id')
        comment=Comment.objects.get(id=comment_id).delete()
        return JsonResponse({'success': True})
    

piro21_Ajax_Pirostagram/apps/users/views.py
from django.shortcuts import render, redirect
from .models import User
from .forms import UserForm
from django.http import JsonResponse
from apps.posts.models import Post

def list(request):
    users=User.objects.all()
    context={'users':users}
    return render(request, 'user_list.html', context)

def create(request):
    if request.method=="GET":
        form=UserForm
        context={'form':form}
        return render(request, 'user_create.html',context)
    
    form=UserForm(request.POST)
    if form.is_valid():
        form.save()
    return redirect('users:list')

def delete(request, pk):
    User.objects.get(id=pk).delete()
    return redirect('users:list')

def update(request, pk):
    user=User.objects.get(id=pk)
    if request.method=="GET":
        form=UserForm(instance=user)
        context={'form':form, 'pk':pk}
        return render(request, 'user_update.html', context)
    
    form=UserForm(request.POST, instance=user)
    if form.is_valid():
        form.save()

    return redirect('users:list')


def search_user(request):
    search_txt = request.GET.get('search_txt')
    users = User.objects.filter(name__icontains=search_txt)
    results = [{'id': user.id, 'name': user.name} for user in users]
    return JsonResponse(results, safe=False)

piro21_Ajax_Pirostagram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}?after">
    {% block head %}
    {% endblock %}
</head>
<body>
    <div>
        <ul>
            <li><a href="/"><i class="bi bi-instagram"></i>instagram</a></li>
            <li><i class="bi bi-house-door-fill"></i>홈</li>
            <li class="base-search"><a href="#" onclick="Search(event)"><i class="bi bi-search"></i>검색</a></li>
            <li><i class="bi bi-compass"></i>탐색 탭</li>
            <li><i class="bi bi-send"></i>메시지</li>
            <li><i class="bi bi-heart"></i>알림</li>
            <li><a href="{% url 'posts:create' %}"><i class="bi bi-plus-square"></i></a>만들기</li>
            <li><i class="bi bi-person-circle"></i>프로필</li>
            <li><i class="bi bi-threads"></i>Threads</li>
            <li><i class="bi bi-list"></i>더 보기</li>
        </ul>
    </div>
    <div id="search-container" style="display:none;">
        <input type="text" id="search-input" placeholder="검색어를 입력하세요" oninput="searchPosts()">
        <button onclick="searchPosts()">검색</button>
        <ul id="search-results"></ul>
    </div>
    {% block content %}
    {% endblock content %}
    <script>
        function Search(event) {
            event.preventDefault();
            let searchContainer = document.getElementById('search-container');
            searchContainer.style.display = searchContainer.style.display === 'none' || searchContainer.style.display === '' ? 'block' : 'none';
        }

        const requestSearch = new XMLHttpRequest();

        const searchPosts = () => {
            const query = document.getElementById('search-input').value;
            if (query.length > 0) {
                const url = `{% url "posts:search" %}?search_txt=${query}`;
                requestSearch.open('GET', url, true);
                requestSearch.onreadystatechange = handleSearchResponse;
                requestSearch.send();
            } 
            else {
                document.getElementById('search-results').innerHTML = '';
            }
        };
        const handleSearchResponse = () => {
            if (requestSearch.readyState === XMLHttpRequest.DONE) {
                if (requestSearch.status < 400) {
                    const data = JSON.parse(requestSearch.responseText);
                    const searchResults = document.getElementById('search-results');
                    searchResults.innerHTML = '';
                    data.forEach((post) => {
                        const li = document.createElement('li');
                        li.innerHTML = `<strong>${post.title}</strong><br>
                                        <em>By: ${post.author} on ${post.created_at}</em><br>
                                        ${post.image ? `<img src="${post.image}" alt="Post Image" style="width:100px;height:100px;"><br>` : ''}
                                        <p>${post.content}</p>`;
                        searchResults.appendChild(li);
                    });
                }
            }
        };
    </script>
</body>
</html>

piro21_Ajax_Pirostagram/templates/post_create.html
{% extends 'base.html' %}

{% block head %}
    <title>post_create</title>
{% endblock %}

{% block content %}
<div class="post-create">
    <form 
        action="{% url 'posts:create' %}"
        method="post"
        enctype="multipart/form-data">
        {% csrf_token %} {{ form.as_p }}
        <button class="btn btn-success">등록하기</button>
    </form>
</div>
{% endblock %}

piro21_Ajax_Pirostagram/templates/post_detail.html
<!-- post_detail.html -->

{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ author.name }}의 게시글</title>

{% endblock %}

{% block content %}
<div class="post-detail">
    <h1>{{ author.name }}의 게시글</h1>
    <div>
        {% for post in posts %}
        <div class="item post-id-{{ post.id }}">
            {% if post.image.url %}
                <img src="{{ post.image.url }}" alt="대체텍스트">
            {% else %}
                <img src="{% static 'posts/image/no_img.png' %}" alt="">
            {% endif %}
            <div class="info">
                {{ post.title }}
                {{ post.text }}
                <button class="post__like" onclick="onClickLike({{ post.id }})">
                    <i class="bi {% if post.id in user_liked_posts %}bi-heart-fill{% else %}bi-heart{% endif %}" id="heart-icon-{{ post.id }}"></i>
                    <span class="like-count" id="like-count-{{ post.id }}">{{ post.like }}</span>
                </button>
                <a href="{% url 'posts:update' post.id %}">수정</a>
                <a href="{% url 'posts:delete' post.id %}">삭제</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            document.querySelectorAll('.post-id-{{ post.id }}').forEach(post => {
                const postId = post.classList[1].split('-')[2];
                const heartIcon = document.getElementById(`heart-icon-${postId}`);
                if (localStorage.getItem(`liked-${postId}`) === 'true') {
                    heartIcon.classList.add('bi-heart-fill');
                    heartIcon.classList.remove('bi-heart');
                }
            });
        });

        const requestLike = new XMLHttpRequest();

        const onClickLike = (id) => {
            const heartIcon = document.getElementById(`heart-icon-${id}`);
            const isLiked = heartIcon.classList.contains("bi-heart-fill");
            const url = "{% url 'posts:like_ajax' %}";
            requestLike.open("POST", url, true);
            requestLike.setRequestHeader(
                "Content-Type",
                "application/json;charset=UTF-8"
            );
            requestLike.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            requestLike.send(JSON.stringify({ id: id, type: isLiked ? "cancel" : "like" }));
        };

        requestLike.onreadystatechange = () => {
            if (requestLike.readyState === XMLHttpRequest.DONE) {
                if (requestLike.status < 400) {
                    const { id, like_count, liked } = JSON.parse(requestLike.responseText);
                    const element = document.querySelector(`.post-id-${id} .like-count`);
                    const heartIcon = document.getElementById(`heart-icon-${id}`);
                    element.innerHTML = like_count;
                    heartIcon.classList.toggle("bi-heart", !liked);
                    heartIcon.classList.toggle("bi-heart-fill", liked);
                }
            }
        };
    </script>
{% endblock %}

piro21_Ajax_Pirostagram/templates/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ author.name }}의 게시글</title>

{% endblock %}

{% block content %}
    <div class="post-container">
        <div class="user-content">
            <a href="{% url 'users:create' %}">유저 등록</a>
            <a href="{% url 'users:list' %}">유저 관리</a>
        </div>
        <form method="get" action="" id="post-sort">
            {{ sort_form.as_p }}
        </form>
        <div class="post-list">
            {% for post in posts %}
            <div class="item post-id-{{ post.id }}">
                {% if post.image.url %}
                    <img src="{{ post.image.url }}" alt="대체텍스트">
                {% endif %}
                <a href="{% url 'posts:detail' post.author.id %}">
                    작성자: {{ post.author }}
                </a><br>
                제목:{{ post.title }}<br>
                내용:{{ post.text }}<br>
                <div class="info">
                    {% if post.author_image %}
                            <img src="{{ post.author_image.url }}">
                    {% endif %}
                    <button class="post__like" onclick="onClickLike({{ post.id }})">
                        <i class="bi {% if post.id in user_liked_posts %}bi-heart-fill{% else %}bi-heart{% endif %}" id="heart-icon-{{ post.id }}"></i>
                        <span class="like-count" id="like-count-{{ post.id }}">{{ post.like }}</span>
                    </button>
                    <div id="comment_list_{{ post.id }}">
                        {% for comment in post.comments.all %}
                        <div class="comment-item" id="comment-{{ comment.id }}">
                            <p>{{ comment.content }}</p>
                            <button onclick="delete_comment({{ comment.id }})">삭제</button><br>
                        </div>
                        {% endfor %}
                    </div>
                    <input type="text" id="comment_{{ post.id }}" name="content" placeholder="댓글 입력">
                    <button onclick="make_comment({{ post.id }})" type="submit">작성</button>
                </div>
            </div><br><br>
            {% endfor %}
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const csrfToken='{{csrf_token}}';
            const sortOptions = document.getElementById('sort-options');  
            if (sortOptions) {
                sortOptions.addEventListener('change', function() {
                    this.form.submit();
                });
            }
        });
    
        document.addEventListener('DOMContentLoaded', () => {
            document.querySelectorAll('.post-id-{{ post.id }}').forEach(post => {
                const postId = post.classList[1].split('-')[2];
                const heartIcon = document.getElementById(`heart-icon-${postId}`);
                if (localStorage.getItem(`liked-${postId}`) === 'true') {
                    heartIcon.classList.add('bi-heart-fill');
                    heartIcon.classList.remove('bi-heart');
                }
            });
        });

        const requestLike = new XMLHttpRequest();

        const onClickLike = (id) => {
            const heartIcon = document.getElementById(`heart-icon-${id}`);
            const isLiked = heartIcon.classList.contains("bi-heart-fill");
            const url = "{% url 'posts:like_ajax' %}";
            requestLike.open("POST", url, true);
            requestLike.setRequestHeader(
                "Content-Type",
                "application/x-www-form-urlencoded"
            );
            requestLike.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            requestLike.send(JSON.stringify({ id: id, type: isLiked ? "cancel" : "like" }));
        };

        requestLike.onreadystatechange = () => {
            if (requestLike.readyState === XMLHttpRequest.DONE) {
                if (requestLike.status < 400) {
                    const { id, like_count, liked } = JSON.parse(requestLike.responseText);
                    const element = document.querySelector(`.post-id-${id} .like-count`);
                    const heartIcon = document.getElementById(`heart-icon-${id}`);
                    element.innerHTML = like_count;
                    heartIcon.classList.toggle("bi-heart", !liked);
                    heartIcon.classList.toggle("bi-heart-fill", liked);
                }
            }
        };


        const requestComment = new XMLHttpRequest();

        const make_comment = (post_id) => {
            const content = document.getElementById(`comment_${post_id}`).value;
            const url = "{% url 'posts:comment_ajax' %}";
            requestComment.open("POST", url, true);
            requestComment.setRequestHeader(
                "Content-Type",
                "application/x-www-form-urlencoded"
            );
            requestComment.send(JSON.stringify({ post_id:post_id, content:content }));
        }

        requestComment.onreadystatechange = () => {
            if (requestComment.readyState === XMLHttpRequest.DONE) {
                if (requestComment.status < 400) {
                    const response = JSON.parse(requestComment.responseText);
                    const post_id = response.post_id;
                    const commentList = document.getElementById(`comment_list_${post_id}`);
                    const newComment = document.createElement('div');
                    
                    newComment.classList.add('comment-item');
                    newComment.id = `comment-${response.comment_id}`;
                    newComment.innerHTML = `
                        <p>${response.content}</p>
                        <button onclick="delete_comment(${response.comment_id})">삭제</button>
                        `;
                    
                    commentList.appendChild(newComment);
                    document.getElementById(`comment_${post_id}`).value = "";
                }
            }
        };

        
        const requestDelete = new XMLHttpRequest();

        const delete_comment = (comment_id) => {
            const url = "{% url 'posts:delete_comment_ajax' %}";
            requestDelete.open('POST', url, true);
            requestDelete.setRequestHeader(
                "Content-Type",
                "application/x-www-form-urlencoded"
            );
            
            requestDelete.onreadystatechange = () => {
                if (requestDelete.readyState === XMLHttpRequest.DONE) {
                    if (requestDelete.status < 400) {
                        const response = JSON.parse(requestDelete.responseText);
                        if (response.success) {
                            const commentElement = document.getElementById(`comment-${comment_id}`);
                            commentElement.remove();
                        } 
                    }
                }
            }
            requestDelete.send(JSON.stringify({ comment_id:comment_id }));
        };
    </script>
{% endblock %}

piro21_Ajax_Pirostagram/templates/post_update.html
{% extends 'base.html' %}

{%block head %}
    <title>post_update</title>
{%endblock%}

{%block content%}
<div class="post-update">
    <form
        action="{% url 'posts:update' pk %}"
        method="post"
        enctype="multipart/form-data">
        {%csrf_token%} {{form.as_p}}
        <button class="btn btn-primary">수정 완료</button>
    </form>
</div>
{%endblock%}

piro21_Ajax_Pirostagram/templates/user_create.html
{% extends 'base.html' %}
{%block head%}
    <title>user_create</title>
{% endblock %}

{%block content%}
<div class="user-create">
    <form
        action="{% url 'users:create' %}"
        method="post"
    >
        {%csrf_token%} {{form.as_p}}
        <button class="btn btn-success">추가하기</button>
    </form>
</div>
{%endblock%}

piro21_Ajax_Pirostagram/templates/user_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>user_list</title>
{% endblock %}

{% block content %}
<div class="user-list">
    {% for user in users %}
    <div>
        <a href="{% url 'users:update' user.pk %}">
            <button type="button" class="btn btn-outline-secondary">
                <span>이름: {{ user.name }}</span>
            </button>
        </a>
    </div>
    {% endfor %}
    <input type="text" id="user-search-input" placeholder="유저 검색">
    <button type="button" onclick="searchUser()">검색</button>
    <ul id="user-search-results"></ul>
</div>

<script>
    const requestUserSearch = new XMLHttpRequest();

    const searchUser = () => {
        const query = document.getElementById('user-search-input').value;
        const url = `{% url 'users:search_user' %}?search_txt=${query}`;
        requestUserSearch.open('GET', url, true);
        requestUserSearch.onreadystatechange = () => {
            if (requestUserSearch.readyState === XMLHttpRequest.DONE) {
                if (requestUserSearch.status < 400) {
                    const data = JSON.parse(requestUserSearch.responseText);
                    const userSearchResults = document.getElementById('user-search-results');
                    userSearchResults.innerHTML = '';
                    data.forEach(user => {
                        const li = document.createElement('li');
                        li.textContent = user.name;
                        userSearchResults.appendChild(li);
                    });
                }
            }
        };
        requestUserSearch.send();
    };
</script>
{% endblock %}

piro21_Ajax_Pirostagram/templates/user_update.html
{% extends 'base.html' %}
{%block head %}
    <title>user_detail</title>
{%endblock%}

{%block content%}
<div class="user-update">
    <form
        action="{% url 'users:update' pk %}"
        method="post"
    >
        {%csrf_token%} {{form.as_p}}
        <button class="btn btn-primary">수정 완료</button>
    </form>
    <form
        action="{% url 'users:delete' pk %}"
        method="post"
    >
        {%csrf_token%}
        <button class="btn btn-danger">삭제</button>
    </form>
</div>
{%endblock%}