SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ideas.urls')),
    path('tools/', include('devTools.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/devTools/urls.py
from django.urls import path
from .views import *

app_name='devTools'

urlpatterns=[
    path('list/', list, name='list'), 
    path('create/', create, name='create'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('update/<int:pk>/', update, name='update'),
]

SWIDEA_SITE/ideas/urls.py
from django.urls import path
from .views import *

app_name='ideas'

urlpatterns=[
    path('', main, name='main'),
    path('create/', create, name='create'),
    path('detail/<int:pk>', detail, name='detail'),
    path('delete/<int:pk>', delete, name='delete'),
    path('update/<int:pk>', update, name='update'),
    path('toggle_star/<int:idea_id>/', toggle_star, name='toggle_star'),
    path('update_interest/<int:idea_id>/<str:action>/', update_interest, name='update_interest'),
]

SWIDEA_SITE/devTools/models.py
from django.db import models

# Create your models here.

class DevTool(models.Model):
    title=models.CharField('이름', max_length=30)
    type=models.CharField('종류', max_length=30)
    explain=models.TextField('개발툴 설명')

    def __str__(self):
        return f'{self.title}'

SWIDEA_SITE/ideas/models.py
from django.db import models
from devTools.models import DevTool
# Create your models here.

class Idea(models.Model):
    title=models.CharField('아이디어명', max_length=30)
    image=models.ImageField('이미지', blank=True, upload_to='image/%Y%m%d')
    explain=models.TextField('아이디어 설명')
    interest=models.IntegerField('아이디어 관심도', default=0)
    tool=models.ForeignKey(DevTool, on_delete=models.CASCADE, verbose_name='예상 개발툴')

class IdeaStar(models.Model):
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('idea',)

SWIDEA_SITE/devTools/forms.py
from django import forms
from .models import DevTool

class DevToolForm(forms.ModelForm):
    class Meta():
        model=DevTool
        fields=('__all__')

SWIDEA_SITE/ideas/forms.py
from django import forms
from .models import Idea

class IdeaForm(forms.ModelForm):
    class Meta():
        model=Idea
        fields=('__all__')

class SortForm(forms.Form):
    SORT_CHOICES = [
        ('등록순', '등록순'),
        ('최신순', '최신순'),
        ('이름순', '이름순'),
        ('찜하기순', '찜하기순'),
    ]
    sort_by = forms.ChoiceField(
        label='정렬',
        choices=[('','--정렬기준--')] + SORT_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'sort-input',
                'id': 'sort-options'
            }
        )
    )

SWIDEA_SITE/devTools/views.py
from django.shortcuts import render, redirect
from .models import DevTool
from ideas.models import Idea
from .forms import DevToolForm

# Create your views here.

def list(request):
    devtools=DevTool.objects.all()
    context={'devtools':devtools}
    return render(request, 'devTools/list.html', context)

def create(request):
    if request.method=="GET":
        form=DevToolForm()
        context={'form':form}
        return render(request, 'devTools/create.html', context)
    
    form=DevToolForm(request.POST)
    if form.is_valid():
        devtools=form.save()
    return redirect('devTools:detail', pk=devtools.pk)

def detail(request, pk):
    devtools=DevTool.objects.get(id=pk)
    related_ideas = Idea.objects.filter(tool=devtools)
    context = {'devtools': devtools, 'related_ideas': related_ideas}
    return render(request, 'devTools/detail.html', context)

def delete(request, pk):
    DevTool.objects.get(id=pk).delete()
    return redirect('devTools:list')

def update(request, pk):
    devtools=DevTool.objects.get(id=pk)
    if request.method=='GET':
        form=DevToolForm(instance=devtools)
        context={'form':form, 'pk':pk}
        return render(request, 'devTools/update.html', context)
    
    form=DevToolForm(request.POST, instance=devtools)
    if form.is_valid():
        form.save()
    return redirect('devTools:detail', pk)

SWIDEA_SITE/ideas/views.py
from django.shortcuts import render, redirect
from .models import Idea, IdeaStar
from django.http import HttpResponse
from .forms import IdeaForm, SortForm
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


def main(request):
    sort_form = SortForm(request.GET)
    sort_by = request.GET.get('sort_by', '등록순')
    
    if sort_by == '찜하기순':
        ideas = Idea.objects.annotate(star_count=Count('ideastar')).order_by('-star_count')
    elif sort_by == '이름순':
        ideas = Idea.objects.order_by('title')
    elif sort_by == '최신순':
        ideas = Idea.objects.order_by('-id')
    else:
        ideas = Idea.objects.order_by('id')

    paginator = Paginator(ideas, 4) 
    page_number = request.GET.get('page')
    
    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    context = {
        'page_obj': page_obj,
        'sort_form': sort_form,
    }
    return render(request, 'ideas/list.html', context)

def toggle_star(request, idea_id):
    if request.method == "POST":
        idea = Idea.objects.get(id=idea_id)

        star, created = IdeaStar.objects.get_or_create(idea=idea)
        if not created:
            star.delete()
            return HttpResponse("false")

        return HttpResponse("true")
    
def update_interest(request, idea_id, action):
    if request.method == "POST":
        idea = Idea.objects.get(id=idea_id)

        if action == 'increase':
            idea.interest += 1
        elif action == 'decrease':
            idea.interest -= 1
        idea.save()
        return HttpResponse(str(idea.interest))
    
def create(request):
    if request.method=="GET":
        form=IdeaForm()
        context={'form':form}
        return render(request, 'ideas/create.html', context)
    
    form=IdeaForm(request.POST, request.FILES)
    if form.is_valid():
        idea=form.save()
        return redirect('ideas:detail', pk=idea.pk)
    context = {'form': form}
    return render(request, 'ideas/create.html', context)

def detail(request, pk):
    idea=Idea.objects.get(id=pk)
    is_starred=IdeaStar.objects.filter(idea=idea).exists()
    context={'idea':idea, 'is_starred':is_starred}
    return render(request, 'ideas/detail.html', context)

def delete(request, pk):
    Idea.objects.get(id=pk).delete()
    return redirect('ideas:main')

def update(request, pk):
    idea=Idea.objects.get(id=pk)
    if request.method=='GET':
        form=IdeaForm(instance=idea)
        context={'form':form, 'pk':pk}
        return render(request, 'ideas/update.html', context)
    
    form=IdeaForm(request.POST, request.FILES, instance=idea)
    if form.is_valid():
        form.save()
        return redirect('ideas:detail', pk=pk)
    context = {'form': form, 'pk': pk}
    return render(request, 'ideas/update.html', context)
    

SWIDEA_SITE/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'ideas/css/style.css' %}?after">
    {% block head %}


    {% endblock %}
</head>
<body>
    <div class="header">
        <h1><a href="/">Hwahyeon's SW idea Manage</a></h1>
        <a href="{% url 'ideas:create' %}">아이디어 등록</a>
        <a href="{% url 'ideas:main' %}">아이디어 관리</a>
        <a href="{% url 'devTools:create' %}">개발툴 등록</a>
        <a href="{% url 'devTools:list' %}">개발툴 관리</a>
    </div>
    {% block content %}

    {% endblock content %}
</body>
</html>

SWIDEA_SITE/templates/devTools/create.html
{% extends 'base.html' %}

{% block head %}
    <title>개발툴 관리</title>
{% endblock %}

{% block content %}
<div class="tool_create">
    <h2>DevTool Register</h2>
    <p>개발툴 등록 페이지 입니다. 자신이 다룰 수 있는 개발툴을 등록해 보세요.</p>
    
    <form 
        action="{% url 'devTools:create' %}"
        method="post"
        enctype="multipart/form-data">
        {% csrf_token %} {{form.as_p}}
        <button>SUBMIT</button>
    </form>
</div>
{% endblock %}

SWIDEA_SITE/templates/devTools/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>개발툴 상세</title>
{% endblock %}

{% block content %}
<div class="tool_detail">
    <h2>DevTool Detail</h2>
    <p>개발툴 세부내용 페이지 입니다. 자신이 다룰 수 있는 개발툴에 대한 상세내용을 확인해 보아요.</p>
    <div class="tool_detail_content">
        <h1>{{devtools.title}}</h1>
        <p>{{devtools.type}}</p>
        <p>{{devtools.explain}}</p>
        <hr>
        <p>만들 수 있는 SW 목록</p>
        <ul>
            {% for idea in related_ideas %}
                <li><a href="{% url 'ideas:detail' idea.pk %}">{{ idea.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
    
    <form action="{% url 'devTools:delete' devtools.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit">삭제</button>
        <a href="{% url 'devTools:list' %}" class="tool_detail_form_a1">목록</a>
        <a href="{% url 'devTools:update' devtools.pk %}" class="tool_detail_form_a2">수정</a>
    </form>
{% endblock %}

SWIDEA_SITE/templates/devTools/list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>개발툴 관리</title>
{% endblock %}

{% block content %}
<div class="tool_list">
    <h2>DevTool List</h2>
    <p style="margin-bottom: 50px;">개발툴 목록 페이지 입니다. 자신이 사용가능한 개발들의 목록을 확인해 보세요.</p>
    {% for devtool in devtools %}
    <div class="tool_list_content">
        <div>
            <a href="{% url 'devTools:detail' devtool.pk %}">
                {{devtool.title}}
            </a>
            <p class="tool_list_p1">{{devtool.type}}</p>
            <p>{{devtool.explain}}</p><br>
        </div>
        <hr>
    </div>
    {% endfor %}
    <footer>
        <div class="pagination">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}">&lt;</a>
            {% else %}
                <a href="?page=1{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}">&lt;</a>
            {% endif %}
            
            <span>{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>
            
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}">&gt;</a>
            {% else %}
                <a href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}">&gt;</a>
            {% endif %}
        </div>
    </footer>
</div>
{% endblock %}

SWIDEA_SITE/templates/devTools/update.html
{% extends 'base.html' %}

{% block head %}
    <title>개발툴 수정</title>
{% endblock %}

{% block content %}
<div class="tool_update">
    <h2>DevTool Detail Update</h2>
    <p>개발툴 세부내용 수정 페이지 입니다. 개발툴에 대해 수정사항이 있으면 고쳐보아요.</p>
    
    <form 
        action="{% url 'devTools:update' pk %}"
        method="post"
        enctype="multipart/form-data">
        {% csrf_token %} {{form.as_p}}
        <button>SUBMIT</button>
    </form>
</div>
{% endblock %}

SWIDEA_SITE/templates/ideas/create.html
{% extends 'base.html' %}

{% block head %}
    <title>아이디어 관리</title>
{% endblock %}

{% block content %}
<div class="idea_create">
    <h2>Idea Register</h2>
    <p>아이디어 등록 페이지 입니다. 당신의 아이디어를 잊지 말고 기록하세요!</p>
    
    <form 
        action="{% url 'ideas:create' %}"
        method="post"
        enctype="multipart/form-data">
        {% csrf_token %} {{form.as_p}}
        <button>SUBMIT</button>
    </form>
</div>
{% endblock %}

SWIDEA_SITE/templates/ideas/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>아이디어 상세</title>
{% endblock %}

{% block content %}
<div class="idea_detail">
    <h2>Idea Detail</h2>
    <p>아이디어 세부내용 페이지 입니다. 당신이 구현하려 한 아이디어들을 자세히 살펴보세요.</p>
    <div class="idea_detail_content">
        {% if idea.image.url != '' %}
            <img src="{{idea.image.url}}" alt="이미지">
        {% else %}
            <p>이미지 없음</p>
        {% endif %}
        <div class="idea_detail_text">
            <h1>{{idea.title}}</h1>
            <span class="star-btn {% if idea.ideastar_set.count > 0 %}gold{% endif %}" data-idea-id="{{ idea.id }}" style="top:300px; right:245px;">
                ★
            </span>
            <p>1. 아이디어 관심도<br>{{idea.interest}}</p>
            <p class="idea_detail_text_p">2. 예상 개발 툴<br>
                <a href="{% url 'devTools:detail' idea.tool.pk %}">{{ idea.tool.title }}</a>
            </p>
            <p>3. 아이디어 설명<br>{{idea.explain}}</p>
        </div>
    </div>
    
    <form action="{% url 'ideas:delete' idea.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit">삭제</button>
        <a href="{% url 'ideas:main' %}" class="idea_detail_form_a1">목록</a>
        <a href="{% url 'ideas:update' idea.pk %}" class="idea_detail_form_a2">수정</a>
    </form>
{% endblock %}

SWIDEA_SITE/templates/ideas/list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>아이디어 관리</title>
{% endblock %}

{% block content %}
<div class="idea_list">
    <h2>Idea List</h2>
    <p class="idea_list_ment">나의 아이디어를 잊지 말고 기록해보세요</p>
    <form method="get" action="">
        {{ sort_form.as_p }}
    </form>
    {% for idea in page_obj %}
    <div class="idea-item">
        {%  if idea.image.url != null and idea.image.url != '' %}
            <img src="{{idea.image.url}}" alt="대체텍스트" class="idea-image">
        {% else %}
            <p>이미지 없음</p>
        {% endif %}
        <span class="star-btn {% if idea.ideastar_set.count > 0 %}gold{% endif %}" data-idea-id="{{ idea.id }}">
            ★
        </span>
        <div class="idea_list_content">
            <a href="{% url 'ideas:detail' idea.pk %}">
                {{idea.title}}
            </a>
            <hr>
            <p>예상 개발 툴: {{idea.tool}}</p>
            <div class="interest-buttons">
                아이디어 관심도:
                <button class="interest-btn" data-idea-id="{{ idea.id }}" data-action="increase">+</button>
                <span class="interest-count"> {{ idea.interest }} </span>
                <button class="interest-btn" data-idea-id="{{ idea.id }}" data-action="decrease" style="font-size: 48px;
    margin-top: -26px;">-</button>
                <br><br>
            </div>
        </div>
    </div>
    {% endfor %}
    <footer>
        <div class="pagination">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}">&lt;</a>
            {% else %}
                <a href="?page=1{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}">&lt;</a>
            {% endif %}
            
            <span>{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>
            
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}">&gt;</a>
            {% else %}
                <a href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}">&gt;</a>
            {% endif %}
        </div>
    </div>
    </footer>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const csrfToken='{{csrf_token}}';
        document.getElementById('sort-options').addEventListener('change', function() {
            this.form.submit();
        });

        document.querySelectorAll('.star-btn').forEach(button => {
            button.addEventListener('click', function() {
                const ideaId = this.dataset.ideaId;

                fetch(`/toggle_star/${ideaId}/`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'X-CSRFToken': csrfToken
                    },
                    body: `csrfmiddlewaretoken=${csrfToken}`
                })
                .then(response => response.text())
                .then(text => {
                    this.classList.toggle('gold', text === "true");
                });
            });
        });

        document.querySelectorAll('.interest-btn').forEach(button => {
            button.addEventListener('click', function() {
                const ideaId = this.dataset.ideaId;
                const action = this.dataset.action;

                fetch(`/update_interest/${ideaId}/${action}/`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'X-CSRFToken': csrfToken
                    },
                    body: `csrfmiddlewaretoken=${csrfToken}`
                })
                .then(response => response.text())
                .then(text => {
                    this.closest('.idea-item').querySelector('.interest-count').textContent = text;
                });
            });
        });
    });
</script>

{% endblock %}

SWIDEA_SITE/templates/ideas/update.html
{% extends 'base.html' %}

{% block head %}
    <title>아이디어 수정</title>
{% endblock %}

{% block content %}
<div class="idea_update">
    <h2>Idea Dtail Update</h2>
    <p>아이디어 세부내용 수정 페이지 입니다. 구체화하거나 내용을 변경해 보아요.</p>
    
    <form 
        action="{% url 'ideas:update' pk %}"
        method="post"
        enctype="multipart/form-data">
        {% csrf_token %} {{form.as_p}}
        <button>SUBMIT</button>
    </form>
</div>
{% endblock %}